#!/usr/bin/env bash

xmonad --recompile

HERE=$(dirname $(readlink -f $0))
SCREEN_SIZE=${SCREEN_SIZE:-1904x1071}
XDISPLAY=${XDISPLAY:-:2}
LOG_LEVEL=${LOG_LEVEL:-INFO}
APP=${APP:-alacritty}
if [[ -z $PYTHON ]]; then
    PYTHON=python3
fi

Xephyr +extension RANDR -screen ${SCREEN_SIZE} ${XDISPLAY} -ac &
XEPHYR_PID=$!
(
  sleep 1
  env DISPLAY=${XDISPLAY} QTILE_XEPHYR=1 xmonad $@ &
  XMONAD_PID=$!
  env DISPLAY=${XDISPLAY} ${APP} &
  wait $XMONAD_PID
  kill $XEPHYR_PID
)
