#!/bin/sh
if [ -z $OP_SESSION_my ]; then
    eval $(op signin my)
fi

if [ -d $HOME/.aws ]; then
    read -p '.aws/ folder exists do you want to overwrite everything in it? (y/N): ' input
    case $input in
        [Yy]*) rm -rf $HOME/.aws/*; break;;
        *) echo "Appending configs to existing once. Make sure there are no replicas!"; break;;
    esac
else
    mkdir $HOME/.aws
fi

for data in $(op list items --tags aws-cred | op get item - --fields name,key,secret,key_str,key_secret); do
    skip=$(echo $data | jq -r '.key')
    if [[ $skip != "TEST" ]];then
        key=$(echo $data | jq -r '.key')
        secret=$(echo $data | jq -r '.secret')
        name=$(echo $data | jq -r '.name')

        echo "Adding profile '$name'"
        cat << EOF >> $HOME/.aws/credentials
[$name]
aws_access_key_id=$key
aws_secret_access_key=$secret

EOF
    fi
done
