#!/bin/sh
if [ -z $OP_SESSION_my ]; then
    eval $(op signin my)
fi

CREDS="$HOME/.aws/credentials"
CONFIG="$HOME/.aws/config"

if [ -d $HOME/.aws ]; then
    read -p '.aws/ folder exists do you want to overwrite everything in it? (y/N): ' input
    case $input in
        [Yy]*) rm -rf $HOME/.aws/*; break;;
        *) echo "Appending configs to existing ones. Make sure there are no replicas!"; break;;
    esac
else
    mkdir $HOME/.aws
fi

# Create the credentials
for data in $(op list items --tags aws-cred | op get item - --fields name,key,secret,key_str,key_secret); do
    skip=$(echo $data | jq -r '.key')
    if [[ $skip != "TEST" ]];then
        key=$(echo $data | jq -r '.key')
        secret=$(echo $data | jq -r '.secret')
        name=$(echo $data | jq -r '.name')

        echo "Adding credentials with name '$name'"
        cat << EOF >> $CREDS
[$name]
aws_access_key_id=$key
aws_secret_access_key=$secret

EOF
    fi
done

# Create config file for named profiles
 for data in $(op list items --tags aws-profile | op get item - --fields notes,title); do
    title=$(echo -E $data|jq -r '.title')
    conf=$(echo -E $data|jq -r '.notes')
    echo "Adding profile '$title'"
    cat << EOF >> $CONFIG
[profile $title]
$conf

EOF
done
