#!/bin/bash
# Fetch the repos
git clone https://github.com/chris-marsh/pureline.git
git clone https://github.com/dylanaraps/pfetch.git

# Check if .scripts exists.
if [ -d $HOME/.scripts ]; then
	mkdir $HOME/.scripts
	echo "Remember to add $HOME/.scripts to your PATH"
fi

# Add bins to .scripts
cp ~/repos/pureline/pureline ~/.scripts
cp ~/.repos/pfetch/pfetch ~/.scripts
