#!/bin/sh

#alias ls="ls --color=auto"
#alias la="ls -la --color=auto"
#alias ll="ls -l --color=auto"
alias ls="exa"
alias la="exa -la"
alias ll="exa -l"
alias lt="exa -l --tree"


alias pacman="sudo pacman"
alias systemctl="sudo systemctl"

# You never know what you might type
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias vimdiff="nvim -d"

alias config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias sysus="systemctl suspend"

alias grubdate="sudo grub-mkconfig -o /boot/grub/grub.cfg"

# Git stuff
alias gpl="git pull"
alias gps="git push"
alias gco="git checkout"
alias gcom="git commit -am" 

alias refresh-mirrors="echo 'Refreshing mirrors...' &&\
                sudo reflector --country Finland \
                --country Sweden \
                --country Germany \
                --country Norway \
                --country Denmark \
                --country 'United Kingdom' \
                --country Netherlands \
                --country Poland \
                --latest 50 \
                --sort rate \
                --save /etc/pacman.d/mirrorlist &&\
                echo 'Mirrors refreshed.'"

