#!/bin/sh

alias ls="ls --color=auto"
alias la="ls -la --color=auto"
alias ll="ls -l --color=auto"

# You never know what you might type
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias sysus="systemctl suspend"

alias grubdate="sudo grub-mkconfig -o /boot/grub/grub.cfg"

alias sw-brave='brave --user-data-dir=/tmp/foo --unsafely-treat-insecure-origin-as-secure="https://localhost:9443" --ignore-certificate-errors'

alias refresh-mirrors="sudo echo 'Refreshing mirrors...' &&\
                sudo reflector --country Finland \
                --country Sweden \
                --country Germany \
                --country Norway \
                --country Denmark \
                --country 'United Kingdom' \
                --country Netherlands \
                --country Poland \
                --latest 50 \
                --sort rate \
                --save /etc/pacman.d/mirrorlist &&\
                echo 'Mirrors refreshed.'"

