format="""
$directory$git_branch$git_status
$hostname$character
"""

scan_timeout=10

[hostname]
ssh_only=true
format='\([$hostname](green bold)\): '

[username]
show_always=false

[directory]
truncation_symbol='.../'
truncation_length=4

[git_branch]
format="[$symbol$branch]($style)"

[git_status]
