#!/bin/sh
/home/juuso/.scripts/on-startup
sxhkd &


if [[ (xrandr | grep ' connected' | wc -l) -gt 1 ]];
then
    bspwm-set-monitors 2
    notify-send "Using two monitors"
else
    bspwm-set-monitors 1
    notify-send "Using one monitor"
fi

bspc rule -a urxvt state=tiled
