#!/bin/bash


if [ "$1" == "sh" ]; then
    echo "#!/bin/bash" >> get_flag.$1
    chmod 755 get_flag.$1
elif [ "$1" == "py" ]; then
    echo "#!/bin/python" >> get_flag.$1
    chmod 755 get_flag.$1
else
    echo "Unsupported format '$1'"
fi
