#!/bin/bash

HAILER_PATH="$HOME/hailer"
FRONT="$HAILER_PATH/front"
API="$HAILER_PATH/api"
DOCKER="$HAILER_PATH/docker"

echo "Creating folders"
echo "	$FRONT"
mkdir -p "$FRONT"
echo "	$API"
mkdir -p "$API"
echo "	$DOCKER"
mkdir -p "$DOCKER"

echo ""

echo "Cloning hailer-front-2"
git clone -q git@bitbucket.org:hailer/hailer-frontend-2.git $FRONT
echo "Cloning hailer-api"
git clone -q git@bitbucket.org:hailer/hailer-api.git $API
echo "Cloning hailer-docker"
git clone -q git@bitbucket.org:hailer/hailer-docker.git $DOCKER

echo "Done"
