#!/bin/bash

laptop="eDP1"
external="DP1"

office="/home/juuso/.screenlayout/office.sh"
standalone="/home/juuso/.screenlayout/laptop1152.sh"

if xrandr | grep "^$external connected"; then
    echo "external monitor detected"
    sh $office
else
    echo "no external moitors found"
    sh $standalone
fi
